export const CLIENT_ID = '84049100106-h3oj1s01q2og079rrbc9lu6mgc80vnra.apps.googleusercontent.com';
const BASE_SCOPE = [
  'https://www.googleapis.com/auth/calendar.app.created',
  'https://www.googleapis.com/auth/calendar.calendarlist.readonly',
].join(' ');

const ACL_SCOPE = 'https://www.googleapis.com/auth/calendar.acls';

const APP_MARKER = 'Generated by Hebrew Dates App';
const STORAGE = {
  CALENDAR_ID: 'gcal-calendar-id',
  CALENDAR_NAME: 'gcal-calendar-name',
  KNOWN_CALENDARS: 'gcal-known-calendars',
};

let accessToken = null;
let tokenClient = null;
let aclTokenClient = null;
let onAuthChange = null;
let pendingTokenState = null;

function createOAuthState() {
  if (!window.crypto?.getRandomValues) {
    throw new Error('Secure random is unavailable');
  }
  const bytes = new Uint8Array(16);
  window.crypto.getRandomValues(bytes);
  return Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
}

function hasExpectedState(response, expectedState) {
  return typeof expectedState === 'string' && response?.state === expectedState;
}

export function getCalendarName() {
  return localStorage.getItem(STORAGE.CALENDAR_NAME) || 'Hebrew Dates';
}

export function setCalendarName(name) {
  localStorage.setItem(STORAGE.CALENDAR_NAME, name);
}

export function getCalendarId() {
  return localStorage.getItem(STORAGE.CALENDAR_ID);
}

export function setCalendarId(id) {
  if (id) localStorage.setItem(STORAGE.CALENDAR_ID, id);
  else localStorage.removeItem(STORAGE.CALENDAR_ID);
}

function getKnownCalendars() {
  try {
    return JSON.parse(localStorage.getItem(STORAGE.KNOWN_CALENDARS)) || [];
  } catch {
    return [];
  }
}

function saveKnownCalendars(list) {
  localStorage.setItem(STORAGE.KNOWN_CALENDARS, JSON.stringify(list));
}

function addKnownCalendar(id, name) {
  const list = getKnownCalendars();
  const idx = list.findIndex(c => c.id === id);
  if (idx >= 0) {
    if (list[idx].name !== name) {
      list[idx].name = name;
      saveKnownCalendars(list);
    }
  } else {
    list.push({ id, name });
    saveKnownCalendars(list);
  }
}

function removeKnownCalendar(id) {
  const list = getKnownCalendars().filter(c => c.id !== id);
  saveKnownCalendars(list);
}

export function setOnAuthChange(fn) {
  onAuthChange = fn;
}

export function isSignedIn() {
  return !!accessToken;
}

export function initTokenClient() {
  if (!window.google?.accounts?.oauth2) {
    throw new Error('Google Identity Services not loaded yet');
  }
  tokenClient = window.google.accounts.oauth2.initTokenClient({
    client_id: CLIENT_ID,
    scope: BASE_SCOPE,
    include_granted_scopes: true,
    callback: (response) => {
      const expectedState = pendingTokenState;
      pendingTokenState = null;
      if (!hasExpectedState(response, expectedState)) {
        accessToken = null;
        onAuthChange?.(false, 'oauth_state_mismatch');
        return;
      }
      if (response.access_token) {
        accessToken = response.access_token;
        onAuthChange?.(true);
      } else {
        accessToken = null;
        onAuthChange?.(false, response.error || 'no_token');
      }
    },
    error_callback: (err) => {
      pendingTokenState = null;
      accessToken = null;
      onAuthChange?.(false, err.type || 'error');
    },
  });
  aclTokenClient = window.google.accounts.oauth2.initTokenClient({
    client_id: CLIENT_ID,
    scope: ACL_SCOPE,
    include_granted_scopes: true,
    callback: () => {}, // overridden per call
  });
}

export function requestAclAccess() {
  return new Promise((resolve, reject) => {
    if (!aclTokenClient) { reject(new Error('Not initialized')); return; }
    const state = createOAuthState();
    aclTokenClient.callback = (response) => {
      if (!hasExpectedState(response, state)) {
        reject(new Error('OAuth state mismatch'));
        return;
      }
      if (response.access_token) {
        accessToken = response.access_token;
        resolve();
      } else {
        reject(new Error(response.error || 'consent_denied'));
      }
    };
    aclTokenClient.requestAccessToken({ state });
  });
}

export function signIn() {
  if (!tokenClient) throw new Error('Token client not initialized');
  pendingTokenState = createOAuthState();
  tokenClient.requestAccessToken({ state: pendingTokenState });
}

export function signOut() {
  if (accessToken && window.google?.accounts?.oauth2) {
    try { window.google.accounts.oauth2.revoke(accessToken); } catch {}
  }
  accessToken = null;
  onAuthChange?.(false);
}

async function api(method, path, body) {
  if (!accessToken) throw new Error('Not signed in');
  const res = await fetch(`https://www.googleapis.com/calendar/v3${path}`, {
    method,
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      ...(body ? { 'Content-Type': 'application/json' } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (res.status === 401) {
    accessToken = null;
    onAuthChange?.(false, 'token_expired');
    throw new Error('Token expired — please reconnect');
  }
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`API ${method} ${path} failed: ${res.status} ${text}`);
  }
  if (res.status === 204) return null;
  const txt = await res.text();
  return txt ? JSON.parse(txt) : null;
}

export async function ensureCalendar(name) {
  let id = getCalendarId();
  if (id) {
    try {
      const cal = await api('GET', `/calendars/${encodeURIComponent(id)}`);
      if (cal.summary !== name) {
        await api('PATCH', `/calendars/${encodeURIComponent(id)}`, { summary: name });
      }
      addKnownCalendar(id, name);
      return id;
    } catch (err) {
      console.warn('Saved calendar id invalid, will look up by name', err);
      setCalendarId(null);
    }
  }
  // Look for an existing known calendar with this name before creating
  const list = await listCalendars();
  const match = list.find(c => c.name === name);
  if (match) {
    setCalendarId(match.id);
    return match.id;
  }
  return createCalendar(name);
}

export async function createCalendar(name) {
  const created = await api('POST', '/calendars', {
    summary: name,
    description: APP_MARKER,
    timeZone: 'Asia/Jerusalem',
  });
  setCalendarId(created.id);
  addKnownCalendar(created.id, name);
  return created.id;
}

export async function listCalendars() {
  try {
    const data = await api('GET', '/users/me/calendarList');
    const filtered = (data.items || []).filter(c =>
      c.description && c.description.includes(APP_MARKER)
    );
    for (const c of filtered) addKnownCalendar(c.id, c.summary);
    return filtered.map(c => ({ id: c.id, name: c.summary }));
  } catch (err) {
    console.warn('calendarList.list failed, falling back to local tracking', err);
    const known = getKnownCalendars();
    const activeId = getCalendarId();
    if (activeId && !known.find(c => c.id === activeId)) {
      addKnownCalendar(activeId, getCalendarName());
      known.push({ id: activeId, name: getCalendarName() });
    }
    const results = [];
    for (const k of known) {
      try {
        const cal = await api('GET', `/calendars/${encodeURIComponent(k.id)}`);
        if (cal.summary !== k.name) addKnownCalendar(cal.id, cal.summary);
        results.push({ id: cal.id, name: cal.summary });
      } catch (e) {
        removeKnownCalendar(k.id);
      }
    }
    return results;
  }
}

export async function listAllEvents(calendarId, { includeDeleted = true } = {}) {
  const all = [];
  let pageToken;
  do {
    const params = new URLSearchParams({
      maxResults: '2500',
      showDeleted: includeDeleted ? 'true' : 'false',
      singleEvents: 'true',
    });
    if (pageToken) params.set('pageToken', pageToken);
    const data = await api('GET', `/calendars/${encodeURIComponent(calendarId)}/events?${params}`);
    all.push(...(data.items || []));
    pageToken = data.nextPageToken;
  } while (pageToken);
  return all;
}

export async function findEventByICalUID(calendarId, iCalUID) {
  const params = new URLSearchParams({ iCalUID, showDeleted: 'true' });
  const data = await api('GET', `/calendars/${encodeURIComponent(calendarId)}/events?${params}`);
  return data.items?.[0] || null;
}

export function createEvent(calendarId, event) {
  return api('POST', `/calendars/${encodeURIComponent(calendarId)}/events`, event);
}

export function updateEvent(calendarId, eventId, event) {
  return api('PUT', `/calendars/${encodeURIComponent(calendarId)}/events/${eventId}`, event);
}

export function patchEvent(calendarId, eventId, fields) {
  return api('PATCH', `/calendars/${encodeURIComponent(calendarId)}/events/${eventId}`, fields);
}

export function deleteEvent(calendarId, eventId) {
  return api('DELETE', `/calendars/${encodeURIComponent(calendarId)}/events/${eventId}`);
}

function assertOurCalendar(calendarId) {
  const known = getKnownCalendars();
  if (!known.some(c => c.id === calendarId)) {
    throw new Error('Refusing to operate on a calendar not created by this app');
  }
}

export async function listAcl(calendarId) {
  assertOurCalendar(calendarId);
  const data = await api('GET', `/calendars/${encodeURIComponent(calendarId)}/acl`);
  return data.items || [];
}

export function addAcl(calendarId, email, role) {
  assertOurCalendar(calendarId);
  if (role !== 'reader' && role !== 'writer') throw new Error('Invalid role');
  if (typeof email !== 'string' || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
    throw new Error('Invalid email');
  }
  return api(
    'POST',
    `/calendars/${encodeURIComponent(calendarId)}/acl?sendNotifications=true`,
    { role, scope: { type: 'user', value: email } },
  );
}

export function removeAcl(calendarId, ruleId) {
  assertOurCalendar(calendarId);
  return api('DELETE', `/calendars/${encodeURIComponent(calendarId)}/acl/${encodeURIComponent(ruleId)}`);
}
